package aws

// AwsAPIGatewayV2IntegrationResponseResourceType is the Terraform resource type for aws_apigatewayv2_integration_response.
const AwsAPIGatewayV2IntegrationResponseResourceType = "aws_apigatewayv2_integration_response"
