package aws

// AwsAPIGatewayIntegrationResponseResourceType is the Terraform resource type for aws_api_gateway_integration_response.
const AwsAPIGatewayIntegrationResponseResourceType = "aws_api_gateway_integration_response"
